name: Publish new release to Github Pages
# https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site

on:
  push:
    branches: 
      - "master"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build website
        run: |
          npm install
          npm run build
          mv ./build/app.html ./build/index.html
          # touch ./build/.nojeykll
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/
          retention-days: 40
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
