name: Update translations

on:
    workflow_dispatch:
    push:
        paths:
            - "src/lib/i18n/*.json"
    pull_request:
        paths:
            - "src/lib/i18n/*.json"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    translate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Update translations
              run: |
                  sudo apt update -y
                  sudo apt install moreutils -y
                  sudo npm i -g prettier prettier-plugin-svelte
                  bash ./lang.sh
                  sed -ri 's/"version": "'"([[:digit:]]+)\.([[:digit:]]+)\.([[:digit:]]+)"'",/echo \\"version\\": \\"\1.\2.$((\3+1))\\",/e' package.json
                  prettier --write package.json
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add -A
                  git commit -m "chore: update translations"
                  git push
